# generated by datamodel-codegen:
#   filename:  api.json
#   timestamp: 2026-01-15T16:10:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field, constr


class DividendCashAction(Enum):
    REINVEST = "REINVEST"
    TO_ACCOUNT_CASH = "TO_ACCOUNT_CASH"


class AccountBucketDetailedResponse(BaseModel):
    creationDate: Optional[AwareDatetime] = None
    dividendCashAction: Optional[DividendCashAction] = None
    endDate: Optional[AwareDatetime] = None
    goal: Optional[float] = None
    icon: Optional[str] = None
    id: Optional[int] = None
    initialInvestment: Optional[float] = None
    instrumentShares: Optional[Dict[str, float]] = None
    name: Optional[str] = None
    publicUrl: Optional[str] = None


class Status(Enum):
    AHEAD = "AHEAD"
    ON_TRACK = "ON_TRACK"
    BEHIND = "BEHIND"


class Cash(BaseModel):
    availableToTrade: Optional[float] = Field(None, description="Funds available for investing.")
    inPies: Optional[float] = Field(
        None,
        description="It’s the sum of the cash inside of all pies that is not yet invested.",
    )
    reservedForOrders: Optional[float] = Field(
        None,
        description="The amount of cash reserved for pending orders. This cash is not available for placing new trades.",
    )


class DividendDetails(BaseModel):
    gained: Optional[float] = None
    inCash: Optional[float] = None
    reinvested: Optional[float] = None


class DuplicateBucketRequest(BaseModel):
    icon: Optional[str] = None
    name: Optional[str] = None


class EnqueuedReportResponse(BaseModel):
    reportId: Optional[int] = None


class TradingMethod(Enum):
    TOTV = "TOTV"
    OTC = "OTC"


class Type(Enum):
    TRADE = "TRADE"
    STOCK_SPLIT = "STOCK_SPLIT"
    STOCK_DISTRIBUTION = "STOCK_DISTRIBUTION"
    FOP = "FOP"
    FOP_CORRECTION = "FOP_CORRECTION"
    CUSTOM_STOCK_DISTRIBUTION = "CUSTOM_STOCK_DISTRIBUTION"
    EQUITY_RIGHTS = "EQUITY_RIGHTS"


class Type1(Enum):
    ORDINARY = "ORDINARY"
    BONUS = "BONUS"
    PROPERTY_INCOME = "PROPERTY_INCOME"
    RETURN_OF_CAPITAL_NON_US = "RETURN_OF_CAPITAL_NON_US"
    DEMERGER = "DEMERGER"
    INTEREST = "INTEREST"
    CAPITAL_GAINS_DISTRIBUTION_NON_US = "CAPITAL_GAINS_DISTRIBUTION_NON_US"
    INTERIM_LIQUIDATION = "INTERIM_LIQUIDATION"
    ORDINARY_MANUFACTURED_PAYMENT = "ORDINARY_MANUFACTURED_PAYMENT"
    BONUS_MANUFACTURED_PAYMENT = "BONUS_MANUFACTURED_PAYMENT"
    PROPERTY_INCOME_MANUFACTURED_PAYMENT = "PROPERTY_INCOME_MANUFACTURED_PAYMENT"
    RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT = "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT"
    DEMERGER_MANUFACTURED_PAYMENT = "DEMERGER_MANUFACTURED_PAYMENT"
    INTEREST_MANUFACTURED_PAYMENT = "INTEREST_MANUFACTURED_PAYMENT"
    CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT"
    )
    INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT = "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT"
    INTEREST_PAID_BY_US_OBLIGORS = "INTEREST_PAID_BY_US_OBLIGORS"
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS"
    DIVIDENDS_PAID_BY_US_CORPORATIONS = "DIVIDENDS_PAID_BY_US_CORPORATIONS"
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS"
    CAPITAL_GAINS = "CAPITAL_GAINS"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES"
    )
    OTHER_INCOME = "OTHER_INCOME"
    QUALIFIED_INVESTMENT_ENTITY = "QUALIFIED_INVESTMENT_ENTITY"
    TRUST_DISTRIBUTION = "TRUST_DISTRIBUTION"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION"
    CAPITAL_GAINS_DISTRIBUTION = "CAPITAL_GAINS_DISTRIBUTION"
    RETURN_OF_CAPITAL = "RETURN_OF_CAPITAL"
    OTHER_DIVIDEND_EQUIVALENT = "OTHER_DIVIDEND_EQUIVALENT"
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES"
    )
    PTP_UNCHARACTERISED_INCOME = "PTP_UNCHARACTERISED_INCOME"
    MULTIPLE_1042S_TAX_COMPONENTS = "MULTIPLE_1042S_TAX_COMPONENTS"
    DIVIDEND = "DIVIDEND"
    SHORT_TERM_CAPITAL_GAINS = "SHORT_TERM_CAPITAL_GAINS"
    LONG_TERM_CAPITAL_GAINS = "LONG_TERM_CAPITAL_GAINS"
    PROPERTY_INCOME_DISTRIBUTION = "PROPERTY_INCOME_DISTRIBUTION"
    TAX_EXEMPTED = "TAX_EXEMPTED"
    INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT"
    )
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_MANUFACTURED_PAYMENT = "CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT"
    )
    OTHER_INCOME_MANUFACTURED_PAYMENT = "OTHER_INCOME_MANUFACTURED_PAYMENT"
    QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT = (
        "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT"
    )
    TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT = "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT = "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT"
    OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT = (
        "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT"
    )
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT"
    )
    PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT = (
        "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT"
    )
    MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT = (
        "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT"
    )
    DIVIDEND_MANUFACTURED_PAYMENT = "DIVIDEND_MANUFACTURED_PAYMENT"
    SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = "SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = "LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    TAX_EXEMPTED_MANUFACTURED_PAYMENT = "TAX_EXEMPTED_MANUFACTURED_PAYMENT"


class Type2(Enum):
    WITHDRAW = "WITHDRAW"
    DEPOSIT = "DEPOSIT"
    FEE = "FEE"
    TRANSFER = "TRANSFER"


class HistoryTransactionItem(BaseModel):
    amount: Optional[float] = Field(None, description="Amount in the currency of the transaction")
    currency: Optional[str] = Field(None, description="Currency of the transaction")
    dateTime: Optional[AwareDatetime] = None
    reference: Optional[str] = Field(None, description="ID")
    type: Optional[Type2] = None


class Instrument(BaseModel):
    currency: Optional[str] = Field(None, description="Instrument currency in ISO 4217 format.")
    isin: Optional[str] = Field(None, description="ISIN of the instrument.")
    name: Optional[str] = Field(None, description="Name of the instrument.")
    ticker: Optional[str] = Field(
        None, description="Unique instrument identifier.", examples=["AAPL_US_EQ"]
    )


class Name(Enum):
    DELISTED = "DELISTED"
    SUSPENDED = "SUSPENDED"
    NO_LONGER_TRADABLE = "NO_LONGER_TRADABLE"
    MAX_POSITION_SIZE_REACHED = "MAX_POSITION_SIZE_REACHED"
    APPROACHING_MAX_POSITION_SIZE = "APPROACHING_MAX_POSITION_SIZE"
    COMPLEX_INSTRUMENT_APP_TEST_REQUIRED = "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"


class Severity(Enum):
    IRREVERSIBLE = "IRREVERSIBLE"
    REVERSIBLE = "REVERSIBLE"
    INFORMATIVE = "INFORMATIVE"


class InstrumentIssue(BaseModel):
    name: Optional[Name] = None
    severity: Optional[Severity] = None


class InvestmentResult(BaseModel):
    priceAvgInvestedValue: Optional[float] = None
    priceAvgResult: Optional[float] = None
    priceAvgResultCoef: Optional[float] = None
    priceAvgValue: Optional[float] = None


class Investments(BaseModel):
    currentValue: Optional[float] = Field(None, description="Current value of all the investments.")
    realizedProfitLoss: Optional[float] = Field(
        None,
        description="The all-time realised profit loss from all of the trades executed.",
    )
    totalCost: Optional[float] = Field(
        None,
        description="The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own.",
    )
    unrealizedProfitLoss: Optional[float] = Field(
        None,
        description="The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now.",
    )


class MarketRequest(BaseModel):
    extendedHours: Optional[bool] = Field(False, examples=[True])
    quantity: Optional[float] = Field(None, examples=[0.1])
    ticker: Optional[str] = Field(None, examples=["AAPL_US_EQ"])


class InitiatedFrom(Enum):
    API = "API"
    IOS = "IOS"
    ANDROID = "ANDROID"
    WEB = "WEB"
    SYSTEM = "SYSTEM"
    AUTOINVEST = "AUTOINVEST"


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


class Status1(Enum):
    LOCAL = "LOCAL"
    UNCONFIRMED = "UNCONFIRMED"
    CONFIRMED = "CONFIRMED"
    NEW = "NEW"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    REPLACING = "REPLACING"
    REPLACED = "REPLACED"


class Strategy(Enum):
    QUANTITY = "QUANTITY"
    VALUE = "VALUE"


class Type3(Enum):
    LIMIT = "LIMIT"
    STOP = "STOP"
    MARKET = "MARKET"
    STOP_LIMIT = "STOP_LIMIT"


class PaginatedResponseHistoryTransactionItem(BaseModel):
    items: Optional[List[HistoryTransactionItem]] = None
    nextPagePath: Optional[str] = None


class PieRequest(BaseModel):
    dividendCashAction: Optional[DividendCashAction] = None
    endDate: Optional[AwareDatetime] = None
    goal: Optional[float] = Field(
        None, description="Total desired value of the pie in account currency"
    )
    icon: Optional[str] = None
    instrumentShares: Optional[Dict[str, float]] = Field(
        None, examples=[{"AAPL_US_EQ": 0.5, "MSFT_US_EQ": 0.5}]
    )
    name: Optional[str] = None


class PositionWalletImpact(BaseModel):
    currency: Optional[str] = Field(
        None,
        description="The currency code used to represent all the wallet impact information.",
    )
    currentValue: Optional[float] = Field(
        None, description="The current market value of the position."
    )
    fxImpact: Optional[float] = Field(
        None,
        description="The positive or negative impact on the position's value due to currency rate changes.",
    )
    totalCost: Optional[float] = Field(None, description="The total cost paid for the position.")
    unrealizedProfitLoss: Optional[float] = Field(
        None,
        description="The unrealized profit & loss for the position. Calculated as currentValue - totalCost.",
    )


class ReportDataIncluded(BaseModel):
    includeDividends: Optional[bool] = None
    includeInterest: Optional[bool] = None
    includeOrders: Optional[bool] = None
    includeTransactions: Optional[bool] = None


class Status2(Enum):
    Queued = "Queued"
    Processing = "Processing"
    Running = "Running"
    Canceled = "Canceled"
    Failed = "Failed"
    Finished = "Finished"


class ReportResponse(BaseModel):
    dataIncluded: Optional[ReportDataIncluded] = None
    downloadLink: Optional[str] = None
    reportId: Optional[int] = None
    status: Optional[Status2] = None
    timeFrom: Optional[AwareDatetime] = None
    timeTo: Optional[AwareDatetime] = None


class Name1(Enum):
    COMMISSION_TURNOVER = "COMMISSION_TURNOVER"
    CURRENCY_CONVERSION_FEE = "CURRENCY_CONVERSION_FEE"
    FINRA_FEE = "FINRA_FEE"
    FRENCH_TRANSACTION_TAX = "FRENCH_TRANSACTION_TAX"
    PTM_LEVY = "PTM_LEVY"
    STAMP_DUTY = "STAMP_DUTY"
    STAMP_DUTY_RESERVE_TAX = "STAMP_DUTY_RESERVE_TAX"
    TRANSACTION_FEE = "TRANSACTION_FEE"


class Tax(BaseModel):
    chargedAt: Optional[AwareDatetime] = None
    currency: Optional[str] = None
    name: Optional[Name1] = None
    quantity: Optional[float] = None


class Type4(Enum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    BREAK_START = "BREAK_START"
    BREAK_END = "BREAK_END"
    PRE_MARKET_OPEN = "PRE_MARKET_OPEN"
    AFTER_HOURS_OPEN = "AFTER_HOURS_OPEN"
    AFTER_HOURS_CLOSE = "AFTER_HOURS_CLOSE"
    OVERNIGHT_OPEN = "OVERNIGHT_OPEN"


class TimeEvent(BaseModel):
    date: Optional[AwareDatetime] = None
    type: Optional[Type4] = None


class TimeValidity(Enum):
    DAY = "DAY"
    GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"


class Type5(Enum):
    CRYPTOCURRENCY = "CRYPTOCURRENCY"
    ETF = "ETF"
    FOREX = "FOREX"
    FUTURES = "FUTURES"
    INDEX = "INDEX"
    STOCK = "STOCK"
    WARRANT = "WARRANT"
    CRYPTO = "CRYPTO"
    CVR = "CVR"
    CORPACT = "CORPACT"


class TradableInstrument(BaseModel):
    addedOn: Optional[AwareDatetime] = Field(None, description="On the platform since")
    currencyCode: Optional[constr(min_length=3, max_length=3)] = Field(
        None, description="ISO 4217", examples=["USD"]
    )
    extendedHours: Optional[bool] = None
    isin: Optional[str] = None
    maxOpenQuantity: Optional[float] = None
    name: Optional[str] = None
    shortName: Optional[str] = None
    ticker: Optional[str] = Field(None, description="Unique identifier", examples=["AAPL_US_EQ"])
    type: Optional[Type5] = Field(None, examples=["ETF"])
    workingScheduleId: Optional[int] = Field(
        None, description="Get items in the /exchanges endpoint"
    )


class WorkingSchedule(BaseModel):
    id: Optional[int] = None
    timeEvents: Optional[List[TimeEvent]] = None


class AccountBucketInstrumentResult(BaseModel):
    currentShare: Optional[float] = None
    expectedShare: Optional[float] = None
    issues: Optional[List[InstrumentIssue]] = None
    ownedQuantity: Optional[float] = None
    result: Optional[InvestmentResult] = None
    ticker: Optional[str] = None


class AccountBucketInstrumentsDetailedResponse(BaseModel):
    instruments: Optional[List[AccountBucketInstrumentResult]] = None
    settings: Optional[AccountBucketDetailedResponse] = None


class AccountBucketResultResponse(BaseModel):
    cash: Optional[float] = Field(
        None, description="Amount of money put into the pie in account currency"
    )
    dividendDetails: Optional[DividendDetails] = None
    id: Optional[int] = None
    progress: Optional[float] = Field(
        None, description="Progress of the pie based on the set goal", examples=[0.5]
    )
    result: Optional[InvestmentResult] = None
    status: Optional[Status] = Field(None, description="Status of the pie based on the set goal")


class AccountSummary(BaseModel):
    cash: Optional[Cash] = None
    currency: Optional[str] = Field(
        None, description="Primary account currency in ISO 4217 format."
    )
    id: Optional[int] = Field(
        None,
        description="Primary trading account number. This is the same account ID you would see in the Trading 212 web or mobile application.",
    )
    investments: Optional[Investments] = None
    totalValue: Optional[float] = Field(
        None, description="Investments value in your account's primary currency."
    )


class Exchange(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    workingSchedules: Optional[List[WorkingSchedule]] = None


class FillWalletImpact(BaseModel):
    currency: Optional[str] = None
    fxRate: Optional[float] = None
    netValue: Optional[float] = None
    realisedProfitLoss: Optional[float] = None
    taxes: Optional[List[Tax]] = None


class HistoryDividendItem(BaseModel):
    amount: Optional[float] = Field(None, description="In account's primary currency.")
    amountInEuro: Optional[float] = None
    currency: Optional[str] = Field(None, description="The account's primary currency.")
    grossAmountPerShare: Optional[float] = Field(None, description="In instrument currency")
    instrument: Optional[Instrument] = None
    paidOn: Optional[AwareDatetime] = None
    quantity: Optional[float] = None
    reference: Optional[str] = None
    ticker: Optional[str] = None
    tickerCurrency: Optional[str] = None
    type: Optional[Type1] = None


class LimitRequest(BaseModel):
    limitPrice: Optional[float] = Field(None, examples=[100.23])
    quantity: Optional[float] = Field(None, examples=[0.1])
    ticker: Optional[str] = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: Optional[TimeValidity] = Field(None, description="Expiration", examples=["DAY"])


class Order(BaseModel):
    createdAt: Optional[AwareDatetime] = Field(
        None, description="The ISO 8601 formatted date of when the order was created."
    )
    currency: Optional[str] = Field(
        None, description="The currency used for the order in ISO 4217 format."
    )
    extendedHours: Optional[bool] = Field(
        None,
        description="If true, the order is eligible for execution outside regular trading hours.",
    )
    filledQuantity: Optional[float] = Field(
        None,
        description="The number of shares that have been successfully executed. Applicable to quantity orders.",
    )
    filledValue: Optional[float] = Field(
        None,
        description="The total monetary value of the executed portion of the order. Applicable to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms.",
    )
    id: Optional[int] = Field(
        None, description="A unique, system-generated identifier for the order."
    )
    initiatedFrom: Optional[InitiatedFrom] = Field(None, description="How the order was initiated.")
    instrument: Optional[Instrument] = None
    limitPrice: Optional[float] = Field(
        None, description="Applicable to LIMIT and STOP_LIMIT orders."
    )
    quantity: Optional[float] = Field(
        None,
        description="The total number of shares requested. Applicable to quantity orders.",
    )
    side: Optional[Side] = Field(None, description="Indicates whether the order is BUY or SELL.")
    status: Optional[Status1] = Field(
        None, description="The current state of the order in its lifecycle."
    )
    stopPrice: Optional[float] = Field(
        None, description="Applicable to STOP and STOP_LIMIT orders."
    )
    strategy: Optional[Strategy] = Field(
        None,
        description="The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY.",
    )
    ticker: Optional[str] = Field(
        None,
        description="Unique instrument identifier. Get from the /instruments endpoint",
        examples=["AAPL_US_EQ"],
    )
    timeInForce: Optional[TimeValidity] = None
    type: Optional[Type3] = None
    value: Optional[float] = Field(
        None,
        description="The total monetary value of the order. Applicable to value orders.",
    )


class PaginatedResponseHistoryDividendItem(BaseModel):
    items: Optional[List[HistoryDividendItem]] = None
    nextPagePath: Optional[str] = None


class Position(BaseModel):
    averagePricePaid: Optional[float] = Field(
        None, description="Average price paid, in instrument currency, per share."
    )
    createdAt: Optional[AwareDatetime] = Field(
        None, description="The ISO 8601 formatted date of when the position was opened."
    )
    currentPrice: Optional[float] = Field(
        None, description="Current price, in instrument currency, of a single share."
    )
    instrument: Optional[Instrument] = None
    quantity: Optional[float] = Field(None, description="Total quantity of shares owned.")
    quantityAvailableForTrading: Optional[float] = Field(
        None, description="Quantity of shares available for trading."
    )
    quantityInPies: Optional[float] = Field(
        None, description="Quantity of shares currently used in pie."
    )
    walletImpact: Optional[PositionWalletImpact] = Field(
        None,
        description="Collects the financial impact of the position on the user's wallet.",
    )


class PublicReportRequest(BaseModel):
    dataIncluded: Optional[ReportDataIncluded] = None
    timeFrom: Optional[AwareDatetime] = None
    timeTo: Optional[AwareDatetime] = None


class StopLimitRequest(BaseModel):
    limitPrice: Optional[float] = Field(None, examples=[100.23])
    quantity: Optional[float] = Field(None, examples=[0.1])
    stopPrice: Optional[float] = Field(None, examples=[100.23])
    ticker: Optional[str] = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: Optional[TimeValidity] = Field(None, description="Expiration", examples=["DAY"])


class StopRequest(BaseModel):
    quantity: Optional[float] = Field(None, examples=[0.1])
    stopPrice: Optional[float] = Field(None, examples=[100.23])
    ticker: Optional[str] = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: Optional[TimeValidity] = Field(None, description="Expiration", examples=["DAY"])


class Fill(BaseModel):
    filledAt: Optional[AwareDatetime] = None
    id: Optional[int] = None
    price: Optional[float] = None
    quantity: Optional[float] = None
    tradingMethod: Optional[TradingMethod] = None
    type: Optional[Type] = None
    walletImpact: Optional[FillWalletImpact] = None


class HistoricalOrder(BaseModel):
    fill: Optional[Fill] = None
    order: Optional[Order] = None


class PaginatedResponseHistoricalOrder(BaseModel):
    items: Optional[List[HistoricalOrder]] = None
    nextPagePath: Optional[str] = None
